import {FishingGame,CONFIG,FISH,CATCHES,RODS,LURES,BOATS,getCatch,freshSave,validateSave,clamp} from './game.js';
import {AREAS,worldExport,validateWorld} from './world.js';
import {Renderer} from './render.js';
import {Soundscape} from './audio.js';
import {openEditor} from './editor.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=body=>`<svg viewBox="0 0 24 24" aria-hidden="true">${body}</svg>`;
const icons={sound:icon('<path d="M11 5 6 9H3v6h3l5 4zM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>'),mute:icon('<path d="M11 5 6 9H3v6h3l5 4zM16 9l5 6m0-6-5 6"/>'),settings:icon('<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>'),book:icon('<path d="M12 5C8 2 4 3 2 4v15c4-1 7-1 10 1 3-2 6-2 10-1V4c-3-1-7-2-10 1v15M5 7l4 1M5 11l4 1m7-4 3-1m-3 5 3-1"/>'),dock:icon('<path d="M3 12h18M5 12v9m14-9v9M3 8l9-6 9 6M7 11V6m10 5V6M2 19c3-2 4 2 7 0s5 2 8 0 4 1 5 0"/>'),chart:icon('<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5zm6-2v16m6-14v16"/>'),hook:icon('<path d="M15 3v13a6 6 0 1 1-12 0v-4l4 4M12 3h6"/>')};
for(const[id,key]of[['audio','mute'],['settings','settings'],['journal-icon','book'],['chart-icon','chart'],['dock-icon','dock'],['cast-icon','hook']])$('#'+id).innerHTML=icons[key];
let storageWarning='';function load(){try{const raw=localStorage.getItem(CONFIG.saveKey);return raw?validateSave(JSON.parse(raw)):freshSave();}catch{storageWarning='Den gamle lagringen kunne ikke leses. En ny tur er klar.';return freshSave();}}
const game=new FishingGame(load()),renderer=new Renderer(game),audio=new Soundscape(),modal=$('#modal'),content=$('#modal-content');
if(matchMedia('(prefers-reduced-motion: reduce)').matches)game.save.reduced=true;
let modalType='',toastUntil=0,whisperUntil=0,lastUi=0,oldPhase='',journalFish='cod',previousFocus=null,testReturn=null,testKind='editor';const held=new Set();
function persist(){if(testReturn&&testKind==='editor')testReturn.customWorld=game.save.customWorld;try{localStorage.setItem(CONFIG.saveKey,JSON.stringify(testReturn||game.save));}catch{toast('Nettleseren kunne ikke lagre turen.');}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');toastUntil=performance.now()+4800;}
function whisper(text){$('#whisper').textContent=text;$('#whisper').classList.add('visible');whisperUntil=performance.now()+7000;}
function clearInput(){held.clear();game.move=0;game.reeling=false;}
function openModal(type,html){if(!modal.open)previousFocus=document.activeElement;clearInput();game.paused=true;modalType=type;modal.dataset.view=type;content.innerHTML=html;$('#close-modal').hidden=['catch','ending'].includes(type);if(!modal.open)modal.showModal();content.scrollTop=0;}
function closeModal(){if(['catch','ending'].includes(modalType))return;modal.close();modalType='';game.paused=false;clearInput();previousFocus?.focus?.();persist();}
$('#close-modal').onclick=closeModal;modal.addEventListener('cancel',e=>{e.preventDefault();closeModal();});
modal.addEventListener('click',e=>{if(e.target!==modal)return;const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();});
function catchModal(f){
 const first=!game.save.journal[f.id],relic=f.kind==='relic',junk=f.kind==='junk';
 openModal('catch',`<section class="catch-modal ${f.loss?'eldritch':''}"><div class="paper-kicker">${first?'EN NY OPPDAGELSE':'OM BORD'} · ${relic?'NOE HAVET HUSKER':junk?'FRA BUNNEN':'FANGST'}</div><h2 class="paper-title">${f.local}</h2><div class="book-sub">${f.name}</div><div id="catch-art"></div><div class="fish-stats"><div><strong>${f.length} cm</strong>LENGDE</div><div><strong>${f.weight.toFixed(1)} kg</strong>VEKT</div><div><strong>${relic?'Relikvie':f.value+' ◈'}</strong>${relic?'BEHOLDES I LOGGBOKA':'VERDI'}</div></div><p class="paper-copy">${f.text}</p>${f.loss?`<div class="field-note">Behold: −${f.loss} sinnsro. Slipp: +2 sinnsro.${relic?' Relikvien trengs ved Avgrunnsporten.':''}</div>`:''}<div class="paper-actions"><button class="paper-button" id="keep">${relic?'Ta vare på den':junk?'Ta med skrapet':'Legg i fiskekassa'}</button><button class="paper-button secondary" id="release">${junk||relic?'La den gå tilbake':'Slipp fri'}</button></div></section>`);
 $('#catch-art').append(renderer.specimen(f.id));
 for(const[id,keep]of[['keep',true],['release',false]])$('#'+id).onclick=()=>{if(!game.resolveCatch(keep))return;modalType='';modal.close();game.paused=false;toast(keep?(relic?'Relikvien er trygg i loggboka.':`${f.local} er om bord. Kjør hjem når du er klar.`):(junk?'Skrapet gikk tilbake til bunnen.':'Oppdagelsen er ført i loggboka.'));persist();$('#cast').focus();};
}
function journal(){const f=getCatch(journalFish)||FISH[0],known=!!game.save.journal[f.id];openModal('journal',`<div class="book"><section class="book-left"><div class="paper-kicker">FISKERENS FELTNOTATER</div><h2 class="paper-title">${known?f.local:'Ukjent farvann'}</h2><div id="journal-art"></div><p class="paper-copy">${known?f.text:'Skriv ned det du ser. Ikke det du tror du så.'}</p><div class="field-note">${known?f.note:'Du trenger ikke beholde en fangst for å føre den i boka.'}</div>${known?`<p class="book-sub">FUNNET ${game.save.journal[f.id]} GANGER</p>`:''}<div class="paper-divider"></div><p class="paper-copy"><strong>${game.stage.name}</strong> · ${Math.round(game.save.sanity)} sinnsro<br>${game.save.relics.length} av 3 relikvier funnet.</p><p class="field-note">${game.save.relics.length===3?'Forseglingen er samlet. Finn Avgrunnsporten i Dagon’s Reach. Du trenger minst 20 sinnsro for å stenge den.':'Kompass ved kapellet. Journal ved vrakene. Avgud ved porten. Marsh har hørt historien før.'}</p></section><section><div class="paper-kicker">FISK · SKRAP · HEMMELIGHETER</div><h2 class="paper-title">Fangstjournal</h2><p class="book-sub">${Object.keys(game.save.journal).length} AV ${CATCHES.length} OPPDAGET</p><div class="book-grid">${CATCHES.map(v=>`<button class="specimen-tile ${game.save.journal[v.id]?'':'unknown'} ${f.id===v.id?'active':''}" data-fish="${v.id}" aria-label="${game.save.journal[v.id]?v.local:'Ukjent funn'}"><span class="tile-art"></span><span>${game.save.journal[v.id]?v.local:'???'}</span></button>`).join('')}</div></section></div>`);if(known)$('#journal-art').append(renderer.specimen(f.id));for(const b of content.querySelectorAll('[data-fish]')){const art=renderer.specimen(b.dataset.fish);if(!game.save.journal[b.dataset.fish])art.setAttribute('aria-hidden','true');b.querySelector('.tile-art').append(art);b.onclick=()=>{journalFish=b.dataset.fish;journal();};}}
function shop(){
 if(!game.atDock||game.phase!=='ready')return;game.velocity=0;game.anchored=true;const s=game.save,value=s.inventory.reduce((n,id)=>n+getCatch(id).value,0);
 const dialogue={human:'«Vanlig fisk betaler regningene. Husk det.»',touched:'«Du ser sliten ut. Jeg har gjort klar rommet ovenpå.»',changing:'«Hva har skjedd med øynene dine? De andre krever mer for varene nå.»',becoming:'«Du er fortsatt velkommen her. Men slukk lanternen før du går.»',deep:'«Jeg visste at havet ville hente deg til slutt.»'}[game.stage.id];
 openModal('shop',`<div class="shop-layout"><aside class="shop-portrait"><img src="${import.meta.env.BASE_URL}art/old-marsh.png" alt="Old Marsh i fiskebutikken"><div><span>OLD MARSH</span><p>Han kjenner vannet.</p></div></aside><section class="shop-detail"><div class="paper-kicker">${esc(game.area.name)} · VED BRYGGA</div><h2 class="paper-title">Marshs agn & utstyr</h2><p class="paper-copy">${dialogue}</p><div class="shop-summary"><div><strong>${s.inventory.length} fangster · ${value} mynt</strong><p>Du har ${s.money} mynt.</p></div><button id="sell" class="paper-button" ${value?'':'disabled'}>Selg fangsten</button></div><div class="shop-tabs"><button data-shop-tab="gear" class="active">Utstyr</button><button data-shop-tab="licenses">Fiskeløyver</button></div><div id="shop-stock"></div><div class="paper-actions"><button id="rest" class="paper-button secondary">Hvil · +35 sinnsro</button><button id="shop-map" class="paper-button secondary">Se sjøkartet</button><button id="leave" class="paper-button">Til båten</button></div>${game.priceMultiplier>1?'<p class="field-note">Folk er redde. Utstyr og løyver koster 15 % mer til du har fått hvile.</p>':''}</section></div>`);
 const stock=tab=>{for(const b of content.querySelectorAll('[data-shop-tab]'))b.classList.toggle('active',b.dataset.shopTab===tab);$('#shop-stock').innerHTML=tab==='licenses'?AREAS.slice(1).map(a=>`<div class="shop-rod"><div><h3>${a.name}</h3><p>${a.maxDepth} meter · ${a.subtitle}</p></div><button class="paper-button secondary" data-license="${a.id}" ${s.licenses.includes(a.id)||s.money<game.price(a.price)?'disabled':''}>${s.licenses.includes(a.id)?'Løyve i lomma':game.price(a.price)+' ◈'}</button></div>`).join(''):`${RODS.map((r,i)=>`<div class="shop-rod"><div><h3>${r.name}</h3><p>${r.depth} meter · ${r.detail}</p></div><button class="paper-button secondary" data-rod="${i}" ${i!==s.rod+1||s.money<game.price(r.price)?'disabled':''}>${i<=s.rod?'Eid':game.price(r.price)+' ◈'}</button></div>`).join('')}<div class="shop-rod"><div><h3>${BOATS[1].name}</h3><p>14 plasser · 38 % raskere båt</p></div><button id="buy-boat" class="paper-button secondary" ${s.boat||s.money<game.price(180)?'disabled':''}>${s.boat?'Eid':game.price(180)+' ◈'}</button></div>${LURES.map(l=>`<div class="shop-rod"><div><h3>${l.name}</h3><p>${l.detail}</p></div><button class="paper-button secondary" data-lure="${l.id}" ${s.lure===l.id||(!s.lures.includes(l.id)&&s.money<game.price(l.price))?'disabled':''}>${s.lure===l.id?'På linen':s.lures.includes(l.id)?'Bruk':game.price(l.price)+' ◈'}</button></div>`).join('')}`;
  for(const b of content.querySelectorAll('[data-rod]'))b.onclick=()=>buy(()=>game.buyRod(+b.dataset.rod),tab);for(const b of content.querySelectorAll('[data-license]'))b.onclick=()=>buy(()=>game.buyLicense(b.dataset.license),tab);for(const b of content.querySelectorAll('[data-lure]'))b.onclick=()=>buy(()=>{if(s.lures.includes(b.dataset.lure)){s.lure=b.dataset.lure;return true;}return game.buyLure(b.dataset.lure);},tab);if($('#buy-boat'))$('#buy-boat').onclick=()=>buy(()=>game.buyBoat(),tab);
 };
 const buy=(fn,tab)=>{if(fn()){audio.effect('coin');persist();shop();content.querySelector(`[data-shop-tab="${tab}"]`).click();}};
 for(const b of content.querySelectorAll('[data-shop-tab]'))b.onclick=()=>stock(b.dataset.shopTab);stock('gear');$('#sell').onclick=()=>{const n=game.sell();if(n){audio.effect('coin');persist();shop();toast(`Marsh betalte ${n} mynt.`);}};$('#rest').onclick=()=>{game.rest();closeModal();toast('Du sov til lyset kom tilbake. +35 sinnsro.');};$('#leave').onclick=closeModal;$('#shop-map').onclick=chart;
}
function chart(){const s=game.save;const areas=[...AREAS,...(s.customWorld?[s.customWorld.area]:[])];openModal('chart',`<div class="paper-kicker">KYSTEN UTENFOR INNSMOUTH</div><h2 class="paper-title">Marshs sjøkart</h2><p class="paper-copy">${game.atDock?'Velg et farvann. Båten settes ut ved områdets brygge.':'Du kan lese kartet her. Kjør tilbake til brygga for å reise til et annet farvann.'}</p><div class="sea-chart"><svg viewBox="0 0 800 360" preserveAspectRatio="none" aria-label="Seilruter mellom Stillwater Cove, Blackthorn Reef og Dagon’s Reach"><path d="M100 305 Q210 280 275 220T455 157T637 80" fill="none" stroke="currentColor" stroke-width="2" stroke-dasharray="5 7"/><path d="M55 24v34m-17-17h34" stroke="currentColor"/><text x="55" y="18" text-anchor="middle">N</text></svg>${areas.map(a=>`<button class="chart-pin ${s.area===a.id?'current':''}" style="left:${a.map[0]}%;top:${a.map[1]}%" data-pin="${a.id}"><span>${s.licenses.includes(a.id)||a.id==='custom'?'◈':'◇'}</span>${esc(a.name)}</button>`).join('')}</div><div class="map-list">${areas.map(a=>`<div class="map-card ${s.area===a.id?'current':''}"><div><h3>${esc(a.name)}</h3><p>${a.maxDepth} m · ${Math.round(a.width/10)} m farvann</p><small>${s.visited.includes(a.id)?'Besøkt':esc(a.subtitle)}</small></div><button class="paper-button" data-travel="${a.id}" ${!game.atDock||s.area===a.id||(!s.licenses.includes(a.id)&&a.id!=='custom')?'disabled':''}>${s.area===a.id?'Du er her':s.licenses.includes(a.id)||a.id==='custom'?'Reis hit':game.price(a.price)+' ◈ løyve'}</button></div>`).join('')}</div>${game.atDock?'<div class="paper-actions"><button id="map-shop" class="paper-button secondary">Kjøp løyve hos Marsh</button></div>':''}`);
 for(const b of content.querySelectorAll('[data-travel]'))b.onclick=()=>{if(game.visit(b.dataset.travel)){closeModal();renderer.addEffect('area');toast(`${game.area.name}. Kjør ut fra brygga når du er klar.`);}};for(const b of content.querySelectorAll('[data-pin]'))b.onclick=()=>content.querySelector(`[data-travel="${b.dataset.pin}"]`).scrollIntoView({block:'center',behavior:'smooth'});if($('#map-shop'))$('#map-shop').onclick=()=>{shop();content.querySelector('[data-shop-tab="licenses"]').click();};}
function endingChoice(){if(game.save.ending){ending();return;}const gate=game.gateReady;openModal('choice',`<div class="paper-kicker">${gate?'AVGRUNNSPORTEN':'DET SISTE MENNESKELIGE'}</div><h2 class="paper-title">${gate?'Havet venter på svaret ditt.':'Du husker nesten navnet ditt.'}</h2><div id="ending-art"></div><p class="paper-copy">${gate?'Kompasset, journalen og avguden passer sammen. Nedenfor samler de seg. De har en plass til deg.':'Bris presser snuten mot hånda di. Huden din er kald. Vannet under båten føles som hjemme.'}</p><div class="paper-actions"><button id="embrace" class="paper-button">Bli med dem</button>${gate&&game.save.sanity>=20?'<button id="seal" class="paper-button secondary">Forsegl porten · forbli menneske</button>':''}${gate&&game.save.sanity<40&&game.save.relicOrder.join(',')==='compass,journal,idol'?'<button id="prophet" class="paper-button secondary">Si ordene du lærte</button>':''}<button id="resist" class="paper-button secondary">Hold fast ved Bris</button></div>`);$('#ending-art').append(renderer.specimen('idol'));$('#embrace').onclick=()=>{if(game.finish('deep'))ending();};if($('#seal'))$('#seal').onclick=()=>{if(game.finish('human'))ending();};if($('#prophet'))$('#prophet').onclick=()=>{if(game.finish('prophet'))ending();};$('#resist').onclick=()=>{if(game.save.sanity===0)game.save.sanity=1;closeModal();toast('Du velger å holde fast. Kjør hjem og hvil hos Marsh.');};}
function ending(){const kind=game.save.ending,copy={human:['Den som kom hjem','Porten lukker seg. For første gang på mange år peker kompasset nord. Bris sovner før dere er framme ved brygga.'],deep:['En av de dype','Du slipper linen. Så slipper du båten. Vannet lukker seg over gjellene dine, og for første gang kan du puste.'],prophet:['Den nye stemmen','Du sier ordene. Havet tier. I morgen vil de komme til brygga for å høre deg snakke.']}[kind];openModal('ending',`<section class="ending-scene ${kind}"><div class="paper-kicker">THE STILLWATER BELOW</div><h2 class="paper-title">${copy[0]}</h2><div id="ending-art"></div><p class="paper-copy">${copy[1]}</p><p class="field-note">Historien er avsluttet. Du kan fortsette å utforske og samle uten flere tap av sinnsro.</p><div class="paper-actions"><button id="endless" class="paper-button">Fortsett · ${kind==='deep'?'Deep One':'fri fisketur'}</button></div></section>`);$('#ending-art').append(renderer.specimen(kind==='human'?'compass':kind==='deep'?'choir':'idol'));$('#endless').onclick=()=>{game.continueEndless();modalType='';modal.close();game.paused=false;persist();};}
async function toggleAudio(){if(audio.enabled){audio.mute();game.save.muted=true;}else{game.save.muted=!(await audio.start());if(game.save.muted)toast('Trykk på lydknappen en gang til for å starte lyden.');}updateAudio();persist();}
function updateAudio(){const on=audio.enabled;$('#audio').innerHTML=on?icons.sound:icons.mute;$('#audio').setAttribute('aria-label',on?'Slå av lyd':'Slå på lyd');}
function edit(){openEditor({game,renderer,openModal,closeModal,persist,toast,playtest:world=>{testKind='editor';if(!testReturn)testReturn=JSON.parse(JSON.stringify(game.save));game.save=validateSave({...freshSave(),customWorld:world,area:'custom',rod:3,boat:1,lures:['worm','jig','magnet'],licenses:['cove','reef','abyss'],money:500,light:game.save.light,x:world.area.dockX+200});game.phase='ready';game.depth=0;game.velocity=0;game.pending=null;closeModal();$('#test-banner').hidden=false;renderer.lastArea='';$('#test-banner').firstChild.textContent='Spilltest · ';}});}
$('#end-test').onclick=()=>{if(testReturn){game.save=validateSave(testReturn);testReturn=null;game.phase='ready';game.pending=null;game.depth=0;game.velocity=0;game.move=0;$('#test-banner').hidden=true;renderer.lastArea='';persist();if(testKind==='editor')edit();}};
function settings(){openModal('settings',`<div class="paper-kicker">EN STUND PÅ VANNET</div><h2 class="paper-title">Din fisketur</h2><div class="settings-row"><label for="sound-setting">Lyd og musikk</label><input id="sound-setting" type="checkbox" ${audio.enabled?'checked':''}></div><div class="settings-row"><label for="reduced">Roligere bevegelser</label><input id="reduced" type="checkbox" ${game.save.reduced?'checked':''}></div><div class="settings-row"><label for="light">Lys over vannet</label><select id="light"><option value="auto">Følg døgnet</option><option value="dawn">Morgengry</option><option value="day">Dag</option><option value="dusk">Skumring</option><option value="night">Natt</option></select></div><div class="settings-row"><label for="lure">Agn på linen</label><select id="lure">${LURES.filter(l=>game.save.lures.includes(l.id)).map(l=>`<option value="${l.id}">${l.name}</option>`).join('')}</select></div><p class="instructions"><strong>Slik fisker du</strong><br>Trykk pilene for å kjøre; trykk igjen eller bruk ankeret for å stoppe. Hold for korte manøvre. Tastatur: ← → eller A/D. Brygga er et fysisk sted: kjør helt bort, og velg «Legg til».<br>Kast linen, senk den med glidebryteren eller ↑ ↓, og vent på napp. Under vann følger kameraet kroken.<br>Trykk for å sveive; trykk igjen for slakk. På tastatur holder du Space for å sveive og slipper for slakk.<br>J: loggbok · M: kart · B: legg til · P: Bris · Esc: meny.</p><div class="paper-actions"><button id="resume" class="paper-button">Tilbake til vannet</button><button id="editor-open" class="paper-button secondary">Lag ditt eget brett</button><button id="new-trip" class="paper-button secondary">Ny fisketur</button></div><p class="build-note">Fangster og framgang lagres på denne enheten.</p>`);$('#light').value=game.save.light;$('#lure').value=game.save.lure;$('#sound-setting').onchange=toggleAudio;$('#reduced').onchange=e=>{game.save.reduced=e.target.checked;persist();};$('#light').onchange=e=>{game.save.light=e.target.value;persist();};$('#lure').onchange=e=>{game.save.lure=e.target.value;persist();};$('#resume').onclick=closeModal;$('#editor-open').onclick=edit;$('#new-trip').onclick=()=>{openModal('reset','<h2 class="paper-title">Begynne på nytt?</h2><p class="paper-copy">Denne turens fangster, penger og framgang slettes. Det egne brettet ditt beholdes.</p><div class="paper-actions"><button id="reset-confirm" class="paper-button">Start ny tur</button><button id="reset-cancel" class="paper-button secondary">Behold turen</button></div>');$('#reset-cancel').onclick=settings;$('#reset-confirm').onclick=()=>{const custom=game.save.customWorld;game.save={...freshSave(),customWorld:custom};testReturn=null;$('#test-banner').hidden=true;game.phase='ready';game.pending=null;game.depth=0;game.move=0;game.velocity=0;game.events=[];renderer.lastArea='';audio.mute();updateAudio();closeModal();persist();};};}
$('#settings').onclick=settings;$('#audio').onclick=toggleAudio;$('#journal').onclick=journal;$('#chart').onclick=chart;$('#dock').onclick=shop;$('#pet').onclick=()=>game.pet();$('#anchor').onclick=()=>game.anchor();$('#cast').onclick=()=>{if(game.gateReady&&game.phase==='ready')endingChoice();else game.action();if(!game.save.muted&&!audio.enabled)audio.start().then(updateAudio);};$('#cancel').onclick=()=>game.cancel();$('#depth').oninput=e=>game.setDepth(+e.target.value);$('#depth').onchange=persist;
// Prevent long-press selection/callouts only on game surfaces, never editor fields.
for(const el of document.querySelectorAll('#game button,#game canvas,#depth'))el.addEventListener('contextmenu',e=>e.preventDefault());
for(const[id,d]of[['left',-1],['right',1]]){const b=$('#'+id);let pressedAt=0,wasMoving=false,tapped=false;b.onpointerdown=e=>{e.preventDefault();pressedAt=performance.now();wasMoving=game.move===d;tapped=false;game.setMove(d);b.setPointerCapture(e.pointerId);};b.onpointerup=e=>{e.preventDefault();tapped=performance.now()-pressedAt<260;if(!tapped||wasMoving)game.move=0;persist();};b.onpointercancel=()=>{tapped=false;game.move=0;};b.onlostpointercapture=()=>{if(!tapped)game.move=0;};b.onclick=e=>{if(e.detail===0){if(game.move===d)game.move=0;else game.setMove(d);}};}
document.addEventListener('keydown',e=>{if(modal.open||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','KeyA','KeyD'].includes(e.code))e.preventDefault();held.add(e.code);if(['ArrowLeft','KeyA'].includes(e.code))game.setMove(-1);if(['ArrowRight','KeyD'].includes(e.code))game.setMove(1);if(e.code==='ArrowUp')game.setDepth(game.save.targetDepth-2);if(e.code==='ArrowDown')game.setDepth(game.save.targetDepth+2);if(e.repeat)return;if(e.code==='Space'){if(game.phase==='fight')game.reeling=true;else $('#cast').click();}if(e.code==='KeyJ')journal();if(e.code==='KeyM')chart();if(e.code==='KeyB')shop();if(e.code==='KeyP')game.pet();if(e.code==='KeyX')game.anchor();if(e.code==='Escape')settings();});
document.addEventListener('keyup',e=>{held.delete(e.code);if(['ArrowLeft','ArrowRight','KeyA','KeyD'].includes(e.code))game.move=held.has('ArrowLeft')||held.has('KeyA')?-1:held.has('ArrowRight')||held.has('KeyD')?1:0;if(e.code==='Space')game.reeling=false;});
window.addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{clearInput();last=performance.now();if(document.hidden){persist();metrics.interruptions++;}});window.addEventListener('pagehide',persist);
function ui(now){
 const g=game,s=g.save,phase=g.phase,text={ready:[g.gateReady?'Møt det som venter':'Kast linen',g.atDock?'Marsh har tent lampen.':Math.abs(g.velocity)>20?'Finn din egen fiskeplass.':'En stille stund på vannet.',g.atDock?'Legg til for handel, hvile og reiser.':'Trykk pilene for å kjøre. Kast for å se under vann.'],casting:['Kaster …','Linen følger kastet.',''],sinking:['Linen synker',`${g.depth.toFixed(1)} meter under overflaten.`,'Du kan justere dybden mens den synker.'],waiting:['Venter på napp','Noe beveger seg der nede.','Vent til fisken biter.'],bite:['Napp! Sett kroken','Der!','Trykk for å sette kroken.'],fight:[g.reeling?'Gi slakk':'Sveiv inn','',''],retrieving:['Tar inn linen','Snart klar til å kjøre.',''],caught:['Fangst om bord','','']}[phase];
 $('#cast-label').textContent=text[0];$('#cast').disabled=['casting','sinking','waiting','retrieving','caught'].includes(phase);$('#cast').classList.toggle('reeling',phase==='fight'&&g.reeling);$('#hint').textContent=text[1];$('#subhint').textContent=text[2];$('#fish-tip').hidden=phase==='fight'||modal.open;$('#fight').hidden=phase!=='fight'||modal.open;$('#fight').classList.toggle('danger',g.tension>.78);$('#fight-label').textContent=g.tension>.78?'GI SLAKK NÅ':g.resistance>.66?'FISKEN TREKKER':'DEN GIR ETTER';$('#tension').style.width=g.tension*100+'%';$('#catch-progress').style.width=g.progress*100+'%';$('#distance').textContent=g.depth.toFixed(1)+' m igjen';$('#catch-progress-label').textContent=Math.round(g.progress*100)+' % inne';
 $('#cancel').hidden=!['casting','sinking','waiting','bite','fight'].includes(phase);$('#left').disabled=$('#right').disabled=$('#anchor').disabled=phase!=='ready';$('#left').setAttribute('aria-pressed',String(g.move===-1));$('#right').setAttribute('aria-pressed',String(g.move===1));$('#anchor').setAttribute('aria-pressed',String(g.anchored));$('#anchor').setAttribute('aria-label',g.anchored?'Løft ankeret':'Senk ankeret');$('#depth').disabled=!['ready','sinking','waiting'].includes(phase);$('#depth').max=g.maxDepth;$('#depth').value=s.targetDepth;$('#depth-value').textContent=Math.round(s.targetDepth)+' m';$('#depth-limit').textContent=g.maxDepth+' m maks';$('#money').textContent=s.money;$('#sanity-bar').style.width=s.sanity+'%';$('#sanity-number').textContent=Math.round(s.sanity);$('#sanity-label').textContent=g.stage.name;$('#location').textContent=g.location;$('#clock').textContent=`DAG ${s.day} · ${{dawn:'MORGENGRY',day:'DAG',dusk:'SKUMRING',night:'NATT'}[renderer.light()]}`;
 $('#journal-count').textContent=Object.keys(s.journal).length+' / '+CATCHES.length;$('#bag-count').textContent=s.inventory.length+' / '+g.capacity+' i kassa';$('#dock').hidden=!g.atDock||phase!=='ready';$('#area-name').textContent=g.area.name;$('#dock-distance').textContent=g.atDock?'⚓ Ved brygga':`${s.x>g.area.dockX?'←':'→'} Brygga · ${Math.round(Math.abs(s.x-g.area.dockX)/100)*10} m`;$('#voyage-boat').style.left=s.x/g.area.width*100+'%';$('#voyage-dock').style.left=g.area.dockX/g.area.width*100+'%';
 if(now>toastUntil)$('#toast').classList.remove('visible');if(now>whisperUntil)$('#whisper').classList.remove('visible');if(oldPhase!==phase){if(phase==='bite')$('#cast').focus({preventScroll:true});oldPhase=phase;}
}
function events(){for(const e of game.events.splice(0)){if(e.type==='save')persist();if(e.type==='toast')toast(e.data);if(['cast','splash','caught','pet','discovery','anchor','area'].includes(e.type))renderer.addEffect(e.type);audio.effect(e.type);if(e.type==='caught')catchModal(e.data);if(e.type==='snap')toast('Linen røk. Gi slakk før måleren fylles.');if(e.type==='pet')toast(e.data?'Bris legger hodet i hånda di. +4 sinnsro.':'Bris blir liggende tett inntil deg.');if(e.type==='discovery')whisper('Under båten sier noe navnet ditt.');if(e.type==='stage')whisper({human:'Du kjenner hånda di igjen.',touched:'Lydene fra dypet er lettere å forstå.',changing:'Det er noe mellom fingrene dine.',becoming:'Du savner vannet. Selv her ute.',deep:'Havet har alltid kjent navnet ditt.'}[e.data.id]);if(e.type==='ending-choice')endingChoice();}}
// Visible, opt-in QA controls. Review scenes use an isolated save; reloading
// or leaving a scene returns to the campaign. Normal play never uses fixtures.
const params=new URLSearchParams(location.search),qa=params.has('qa');
const metrics={frames:[],costs:[],start:0,duration:0,active:false,interruptions:0,result:null,live:[],renderLive:[],layouts:new Set()};
let metricsPanel;
if(qa){
  metricsPanel=document.createElement('aside');metricsPanel.className='quality-panel';metricsPanel.innerHTML='<strong>RUNTIME · GAUNTLET</strong><button id="measure">Mål 120 sekunder</button><button id="portrait">Vis 390 px portrett</button><button id="qa-hide">Skjul målepanel</button><button id="water-test">Test vannkopiering av/på</button><button id="blank-test">Test tegning av/på</button><label for="qa-scene">Isolert testscene</label><select id="qa-scene"><option value="">Velg scene</option><option value="surface">Varm vik</option><option value="depth">Dyp line · 60 m</option><option value="changing">Forvandling · 15 sinnsro</option><option value="deep">Etter Deep One-slutten</option></select><pre id="live-metrics"></pre><pre id="metrics">Klar. 5 s oppvarming + 120 s måling.</pre>';
  $('#game').append(metricsPanel);
  $('#measure').onclick=()=>{metrics.frames=[];metrics.costs=[];metrics.start=performance.now();metrics.active=true;metrics.interruptions=0;metrics.result=null;metrics.layouts.clear();};
  $('#portrait').onclick=()=>{document.documentElement.classList.toggle('view-portrait');$('#portrait').textContent=document.documentElement.classList.contains('view-portrait')?'Vis full bredde':'Vis 390 px portrett';};
  $('#qa-hide').onclick=()=>{metricsPanel.hidden=true;};
  $('#qa-scene').onchange=e=>{const kind=e.target.value;if(!kind)return;if(!testReturn)testReturn=JSON.parse(JSON.stringify(game.save));testKind='qa';const sinister=['changing','deep'].includes(kind);game.save=validateSave({...freshSave(),area:sinister?'abyss':'cove',x:sinister?7850:kind==='depth'?5100:1850,rod:3,boat:1,money:240,sanity:kind==='changing'?15:kind==='deep'?0:100,light:sinister?'night':'dusk',licenses:['cove','reef','abyss'],lures:['worm','jig','magnet'],caught:12,discovery:true,journal:{cod:3,perch:2,eel:2,boot:1,tin:1,net:1,compass:1,journal:1,idol:1},relics:sinister?['compass','journal','idol']:[],relicOrder:sinister?['compass','journal','idol']:[],ending:kind==='deep'?'deep':null,endless:kind==='deep',targetDepth:kind==='depth'?60:12});clearInput();game.phase='ready';game.depth=0;game.velocity=0;game.pending=null;game.events=[];game.paused=false;renderer.lastArea='';if(kind==='depth'){game.cast();game.setDepth(60);}$('#test-banner').hidden=false;$('#test-banner').firstChild.textContent='Isolert testscene · ';ui(performance.now());};
  $('#water-test').onclick=()=>{renderer.skipRefraction=!renderer.skipRefraction;metrics.live=[];metrics.renderLive=[];};
  $('#blank-test').onclick=()=>{renderer.diagnosticBlank=!renderer.diagnosticBlank;metrics.live=[];metrics.renderLive=[];};
  document.addEventListener('keydown',e=>{if(e.code==='F8')metricsPanel.hidden=!metricsPanel.hidden;});
}
function record(now,delta,cost){
  if(qa){metrics.live.push(delta);metrics.renderLive.push(cost);if(metrics.live.length>60){metrics.live.shift();metrics.renderLive.shift();}const sum=metrics.live.reduce((a,b)=>a+b,0);$('#live-metrics').textContent=`${renderer.diagnosticBlank?'KONTROLL UTEN ANIMERT LAG':'HELE SPILLSCENEN'}\nLevert: ${(1000*metrics.live.length/sum).toFixed(1)} fps\nTegning: ${(metrics.renderLive.reduce((a,b)=>a+b,0)/metrics.renderLive.length).toFixed(2)} ms\nSynlighet: ${document.visibilityState}\n${navigator.userAgent}`;}
  if(!metrics.active)return;const age=(now-metrics.start)/1000;
  if(age>5&&age<=125&&!document.hidden){metrics.frames.push(delta);metrics.costs.push(cost);metrics.layouts.add(`${renderer.W}×${renderer.H}`);}
  if(age>=125){
    metrics.active=false;const a=[...metrics.frames].sort((a,b)=>a-b),avg=a.reduce((x,y)=>x+y,0)/Math.max(1,a.length),p=q=>a[Math.min(a.length-1,Math.floor(a.length*q))]||0;
    metrics.result={durationSeconds:120,frames:a.length,averageFps:+(1000/avg).toFixed(2),p95Ms:+p(.95).toFixed(2),p99Ms:+p(.99).toFixed(2),stallsOver50ms:a.filter(x=>x>50).length,meanRenderMs:+(metrics.costs.reduce((a,b)=>a+b,0)/Math.max(1,a.length)).toFixed(2),interruptions:metrics.interruptions,canvas:`${renderer.W}×${renderer.H}`,observedCanvases:[...metrics.layouts],devicePixelRatio:devicePixelRatio,renderer:'Canvas2D / cloud Chrome',gate:metrics.interruptions||!a.length||metrics.layouts.size!==1?'INVALID':p(.95)<=17.5&&p(.99)<=20?'PASS':'FAIL'};
    if(qa)$('#metrics').textContent=JSON.stringify(metrics.result,null,2);
    return;
  }
  if(qa&&Math.floor(now/500)!==Math.floor((now-delta)/500))$('#metrics').textContent=metrics.result?JSON.stringify(metrics.result,null,2):`${age<5?'Oppvarming':'Måler'} ${Math.floor(Math.max(0,age-5))} / 120 s\n${metrics.frames.length} frames\nCanvas ${renderer.W} × ${renderer.H}\nAvbrudd: ${metrics.interruptions}`;
}
let last=performance.now();
function frame(now){const delta=now-last;last=now;const dt=document.hidden?0:Math.min(delta/1000,.25);let remaining=dt;while(remaining>0){const step=Math.min(remaining,.025);game.tick(step);events();remaining-=step;}const start=performance.now();renderer.draw(dt);const cost=performance.now()-start;audio.tick(game.save.played,renderer.light()==='night',game);if(now-lastUi>100){ui(now);lastUi=now;}record(now,delta,cost);requestAnimationFrame(frame);}
renderer.load().then(failures=>{const loading=$('#loading');loading.style.opacity='0';setTimeout(()=>loading.remove(),850);if(failures.length)toast('Noe av grafikken kunne ikke lastes. Spillet bruker enklere reservegrafikk.');else if(storageWarning)toast(storageWarning);ui(performance.now());if(game.save.ending&&!game.save.endless)ending();requestAnimationFrame(frame);});
setInterval(()=>{if(!document.hidden)persist();},15000);
