// A complete authored thread, unlocked by real progress rather than elapsed UI time.
export const STORY=[
 {id:'letter',title:'Brevet som kom for sent',when:()=>true,text:'Far har vært borte i tjue år. Likevel lå brevet hans på dørmatta i går, vått av sjøvann. «Når fyret blinker tre ganger, må noen holde porten lukket.» Jeg tok med Bris og den gamle sjekta tilbake til Stillwater. Marsh ventet ved brygga. Han så ikke overrasket ut.'},
 {id:'marsh',title:'Det Marsh ikke solgte',when:s=>s.caught>0,text:'Marsh veide fangsten, men studerte hendene mine. Far var den siste vokteren, sa han. Tre ting holdt noe sovende: et kompass uten nord, en skipsjournal og en liten avgud. Så sluttet fyret å svare. Kompasset forsvant ved kapellet lengst øst i bukta. Jeg må skaffe en stang som når bunnen der.'},
 {id:'compass',title:'En retning som ikke finnes',when:s=>s.relics.includes('compass'),text:'Kompasset peker gjennom skroget, mot Blackthorn Reef. I lokket står fars initialer og navnet på et skip: Morrow. Marsh husker forliset. Han nekter å fortelle hvem som gikk om bord. Jeg trenger fiskeløyve til revet og linen ned i Klokkedypet.'},
 {id:'reef',title:'Alle klokkene under vann',when:s=>s.visited.includes('reef'),text:'Blackthorn lukter jern og tang. Den gamle ferga ligger i biter under oss. Mellom bygene hører jeg en kirkeklokke, selv om kirken for lengst er skylt bort. Bris følger noe langs rekka. Fars skipsjournal må ligge ved vrakene lengst ute, minst 48 meter ned.'},
 {id:'journal',title:'Den siste vokteren',when:s=>s.relics.includes('journal'),text:'Journalen forteller at far ikke druknet. Han gikk frivillig ned for å kjøpe byen mer tid. På siste side har han tegnet tre tegn: nordnåla, ordet og øyet. Rekkefølgen betyr noe. Han ba meg holde fast ved et minne fra land. Bris sover med hodet på støvelen min.'},
 {id:'change',title:'Håndskriften endrer seg',when:s=>s.sanity<40,text:'Saltvann svir ikke lenger i sprekkene mellom fingrene. Jeg hører ord i motorens dunking. De lover at far fremdeles venter. Marsh sier at et løfte fra dypet alltid kommer med en annen stemme enn den som ga det. Jeg kan ennå dra hjem og hvile. Jeg må huske at det er et valg.'},
 {id:'abyss',title:'Et sted uten strand',when:s=>s.visited.includes('abyss'),text:'På kartet heter dette Dagon’s Reach. Her ute ser horisonten ut som baksiden av en lukket dør. Avguden ligger ved Avgrunnsporten, minst 85 meter ned. Vanlig agn blir ignorert. Blodagn og den tause offerkroken lokker fram dem som vokter bunnen.'},
 {id:'idol',title:'Fars siste spørsmål',when:s=>s.relics.includes('idol'),text:'Avguden er varm i hendene. Tre tegn, tre muligheter. Med sinnet i behold kan jeg forsegle porten. Jeg kan også gi slipp på navnet mitt og svømme ned. Eller, hvis jeg fant kompasset, journalen og avguden i den rekkefølgen, si ordene før de sier meg. Porten ligger lengst ute. Far ba aldri om å bli reddet. Han ba meg velge.'},
 {id:'ending',title:'Den siste siden',when:s=>!!s.ending,text:s=>({human:'Nåla peker nord igjen. Jeg kom hjem med Bris. Far fikk endelig hvile, og byen fikk en morgen uten klokker fra bunnen.',deep:'Jeg skriver ikke med blekk lenger. Far kjenner meg igjen. Over oss ligger en liten tom båt, og et lys som snart vil slukke.',prophet:'Jeg sa ordene. Havet stilnet. Nå venter byen ved brygga hver morgen. Jeg vet ikke om jeg har reddet dem, eller lært dem å vente på det samme som meg.'}[s.ending])}
];
export function objective(s){if(s.ending)return 'Historien er avsluttet. Farvannet er ditt.';if(!s.caught)return 'Fang en fisk og finn tilbake til Marsh.';if(!s.relics.includes('compass'))return 'Finn kompasset ved Det sunkne kapellet · øst i Stillwater · minst 24 m.';if(!s.licenses.includes('reef'))return 'Kjøp fiskeløyve til Blackthorn Reef hos Marsh.';if(!s.relics.includes('journal'))return 'Finn skipsjournalen i Klokkedypet · Blackthorn · minst 48 m.';if(!s.licenses.includes('abyss'))return 'Kjøp løyve til Dagon’s Reach. Skaff en stang for minst 85 m.';if(!s.relics.includes('idol'))return 'Finn avguden ved Avgrunnsporten · Dagon’s Reach · minst 85 m.';return 'Kjør lengst ut til Avgrunnsporten. Minst 20 sinnsro lar deg forsegle den.';}
