import test from 'node:test';
import assert from 'node:assert/strict';
import {FishingGame,freshSave,validateSave,CONFIG,getCatch,stageFor} from '../game.js';
import {AREAS,validateWorld,worldExport} from '../world.js';
function advance(g,seconds,hz=60){for(let i=0;i<Math.ceil(seconds*hz);i++)g.tick(1/hz);}
function catchOne(g,keep=true,hz=60,fixed=false){assert.equal(g.cast(),true);let seconds=0;while(g.phase!=='bite'&&seconds<35){g.tick(1/hz);seconds+=1/hz;}assert.equal(g.phase,'bite');g.action();while(g.phase==='fight'&&seconds<90){if(fixed)g.reeling=g.elapsed%4<2.6;else if(g.tension>.65)g.reeling=false;else if(g.tension<.18)g.reeling=true;g.tick(1/hz);seconds+=1/hz;}assert.equal(g.phase,'caught');const id=g.pending.id;g.resolveCatch(keep);return{id,seconds};}
function dock(g){g.paused=false;g.setMove(g.save.x>g.area.dockX?-1:1);let n=0;while(!g.atDock&&n++<5000)g.tick(1/60);assert.equal(g.atDock,true);g.anchor();g.paused=true;}
test('physical sailing -> catching -> return to dock -> sale -> upgrade -> abnormal catch -> reload',()=>{const g=new FishingGame(freshSave(),()=>.2);g.setMove(1);advance(g,6);g.anchor();assert.ok(g.save.x>1800);assert.equal(g.save.facing,1);assert.equal(catchOne(g).id,'cod');assert.equal(catchOne(g).id,'cod');assert.equal(g.sell(),0);dock(g);assert.equal(g.save.facing,-1);assert.equal(g.sell(),76);assert.equal(g.sell(),0);assert.equal(g.buyRod(1),true);assert.equal(g.save.money,6);assert.equal(g.buyRod(1),false);g.paused=false;g.setMove(1);advance(g,5);g.anchor();g.setDepth(24);assert.equal(catchOne(g).id,'eel');assert.equal(g.save.sanity,86);assert.equal(g.resolveCatch(true),false);const restored=new FishingGame(JSON.parse(JSON.stringify(g.save)));assert.equal(restored.save.money,6);assert.equal(restored.save.rod,1);assert.deepEqual(restored.save.inventory,['eel']);assert.equal(restored.save.journal.eel,1);});
test('each area has a physical dock, thousands of travel units and licensed travel cannot teleport home',()=>{const g=new FishingGame({...freshSave(),money:1000},()=>.2);g.paused=true;assert.equal(g.buyLicense('reef'),false);assert.equal(g.visit('reef'),false);dock(g);assert.equal(g.buyLicense('reef'),true);assert.equal(g.buyLicense('reef'),false);assert.equal(g.visit('reef'),true);assert.equal(g.save.x,AREAS[1].dockX);assert.equal(g.atDock,true);g.paused=false;g.setMove(1);advance(g,12);g.anchor();assert.ok(g.save.x>3000);g.paused=true;assert.equal(g.sell(),0);assert.equal(g.visit('cove'),false);dock(g);assert.equal(g.visit('cove'),true);});
test('depth is animated, can change while waiting, and cancellation retrieves before sailing',()=>{const g=new FishingGame(freshSave(),()=>.3);g.cast();advance(g,.8);assert.equal(g.depth,0);assert.equal(g.phase,'casting');advance(g,.6);assert.equal(g.phase,'sinking');assert.ok(g.depth>0&&g.depth<12);advance(g,2);assert.equal(g.phase,'waiting');g.setDepth(18);assert.equal(g.phase,'sinking');advance(g,.25);assert.ok(g.depth>12&&g.depth<18);g.cancel();assert.equal(g.phase,'retrieving');const x=g.save.x;g.setMove(1);advance(g,.5);assert.equal(g.save.x,x);advance(g,.5);assert.equal(g.phase,'ready');assert.equal(g.depth,0);});
test('junk and location-bound relics have distinct utility; releasing preserves humanity',()=>{const g=new FishingGame({...freshSave(),caught:1,discovery:true,rod:1,x:5400,targetDepth:30},()=>.2);assert.equal(catchOne(g).id,'compass');assert.deepEqual(g.save.relics,['compass']);assert.equal(g.save.inventory.length,0);assert.equal(g.save.sanity,95);g.save.lure='magnet';assert.equal(catchOne(g).id,'boot');assert.deepEqual(g.save.inventory,['boot']);assert.equal(g.save.sanity,95);g.save.lure='worm';g.save.discovery=false;assert.equal(catchOne(g,false).id,'eel');assert.equal(g.save.sanity,97);assert.equal(g.save.journal.eel,1);});
test('all five transformation stages and all three ending gates are real and persistent',()=>{assert.deepEqual([100,69,39,19,0].map(v=>stageFor(v).id),['human','touched','changing','becoming','deep']);const save={...freshSave(),area:'abyss',licenses:['cove','reef','abyss'],x:8200,relics:['compass','journal','idol'],relicOrder:['compass','journal','idol'],sanity:30};for(const kind of['human','deep','prophet']){const g=new FishingGame(save);assert.equal(g.gateReady,true);assert.equal(g.finish(kind),true);assert.equal(g.finish(kind),false);const restored=new FishingGame(JSON.parse(JSON.stringify(g.save)));assert.equal(restored.save.ending,kind);assert.equal(restored.continueEndless(),true);}const g=new FishingGame({...save,sanity:19});assert.equal(g.finish('human'),false);g.save.x=500;assert.equal(g.finish('deep'),false);g.save.sanity=0;assert.equal(g.finish('deep'),true);});
test('keeping cursed catches triggers transformation; dock rest allows a human route',()=>{const g=new FishingGame({...freshSave(),sanity:72});g.phase='caught';g.pending=getCatch('eel');assert.equal(g.resolveCatch(true),true);assert.equal(g.stage.id,'touched');assert.ok(g.events.some(e=>e.type==='stage'));g.save.sanity=10;g.phase='caught';g.pending=getCatch('eel');g.resolveCatch(true);assert.equal(g.save.sanity,0);assert.ok(g.events.some(e=>e.type==='ending-choice'));dock(g);g.rest();assert.equal(g.save.sanity,35);assert.equal(g.save.day,2);});
test('same timed input behaves consistently at 30, 60 and 120 Hz',()=>{const r=[30,60,120].map(hz=>{const g=new FishingGame(freshSave(),()=>.2);g.setMove(1);advance(g,3,hz);g.anchor();const x=g.save.x;return{x,time:catchOne(g,true,hz,true).seconds};});assert.ok(Math.max(...r.map(v=>v.x))-Math.min(...r.map(v=>v.x))<6);assert.ok(Math.max(...r.map(v=>v.time))-Math.min(...r.map(v=>v.time))<.4);});
test('pause, full hold and uninterrupted reeling cannot duplicate or bypass fishing outcomes',()=>{const g=new FishingGame(freshSave(),()=>.2);g.cast();advance(g,7);assert.equal(g.phase,'bite');g.action();g.paused=true;const elapsed=g.elapsed;advance(g,20);assert.equal(g.elapsed,elapsed);g.paused=false;advance(g,18);assert.equal(g.phase,'ready');assert.ok(g.events.some(e=>e.type==='snap'));assert.equal(g.save.caught,0);g.save.inventory=Array(8).fill('cod');assert.equal(g.cast(),false);g.save.sanity=50;assert.equal(g.pet(),true);assert.equal(g.pet(),false);});
test('old save migrates without losing purchases, money or catches; bad input is bounded',()=>{const s=validateSave({version:2,money:266,rod:2,sanity:86,inventory:['eel'],journal:{eel:1},x:.79,caught:3});assert.equal(s.version,4);assert.equal(s.money,266);assert.equal(s.rod,2);assert.equal(s.x,760);assert.deepEqual(s.inventory,['eel']);const invalid=validateSave({version:3,money:'Infinity',sanity:-500,rod:999,inventory:Array(22).fill('cod').concat('bogus'),journal:{cod:2,eel:'many'},x:NaN});assert.equal(invalid.money,20);assert.equal(invalid.inventory.length,8);assert.deepEqual(invalid.journal,{cod:2});assert.equal(invalid.x,760);});
test('visual editor export -> validate -> save -> reload -> playable custom map, rejecting unsafe structures',()=>{const raw=worldExport(AREAS[0]);raw.area.name='Testvika';raw.area.dockX=800;raw.area.objects[0].x=2200;const a=validateWorld(raw);assert.equal(a.id,'custom');const g=new FishingGame({...freshSave(),customWorld:worldExport(a)});dock(g);assert.equal(g.visit('custom'),true);assert.equal(g.area.name,'Testvika');assert.equal(g.save.x,800);const restored=new FishingGame(JSON.parse(JSON.stringify(g.save)));assert.equal(restored.area.objects[0].x,2200);const bad=structuredClone(raw);bad.area.objects[0].type='javascript:alert(1)';assert.throws(()=>validateWorld(bad));bad.area.objects=[];bad.area.width=Infinity;assert.throws(()=>validateWorld(bad));});
test('fish investigate, nibble, refuse or commit; premature strikes and repeated twitches scare them',()=>{
 const setup=r=>{const g=new FishingGame({...freshSave(),caught:2,discovery:true},()=>r);g.phase='waiting';g.pending=getCatch('cod');g.waitFor=0;g.depth=12;return g;};
 const take=setup(.1);advance(take,.1);assert.equal(take.phase,'nibbling');advance(take,1);assert.equal(take.phase,'bite');
 const refuse=setup(.99);advance(refuse,.1);assert.equal(refuse.phase,'nibbling');advance(refuse,2.5);assert.equal(refuse.phase,'waiting');assert.ok(refuse.events.some(e=>e.type==='depart'));assert.equal(refuse.save.caught,2);
 const early=setup(.1);advance(early,.1);early.action();assert.equal(early.phase,'waiting');assert.equal(early.progress,0);
 const twitch=setup(.1);twitch.waitFor=100;for(let n=0;n<4;n++){assert.equal(twitch.twitch(),true);advance(twitch,.7);}assert.ok(twitch.events.some(e=>e.type==='depart'));
});
test('bait preferences change real encounter weights in the same habitat',()=>{
 function sample(lure){let seed=17;const rng=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const g=new FishingGame({...freshSave(),area:'reef',licenses:['cove','reef'],x:4200,rod:3,caught:20,discovery:true,lures:['worm','jig','blood'],lure},rng);g.depth=75;const counts={};for(let n=0;n<600;n++){const id=g.selectCatch().id;counts[id]=(counts[id]||0)+1;}return counts;}
 const jig=sample('jig'),blood=sample('blood');assert.ok(jig.squid>blood.squid*1.3);assert.ok(blood.eel>jig.eel);assert.equal(jig.choir,undefined);
});
test('boat ownership, switching capacity and equipment effects survive save migration',()=>{
 const g=new FishingGame({...freshSave(),x:480,money:2500});g.paused=true;assert.equal(g.buyBoat(2),true);assert.equal(g.capacity,22);assert.equal(g.buyBoat(2),false);g.save.inventory=Array(20).fill('cod');assert.equal(g.equipBoat(0),false);g.sell();assert.equal(g.equipBoat(0),true);assert.equal(g.buyEquipment('line'),true);assert.equal(g.buyEquipment('reel'),true);assert.equal(g.buyEquipment('lamp'),true);assert.equal(g.buyEquipment('lamp'),false);
 const migrated=validateSave({...g.save,version:3,boat:1,boats:undefined});assert.ok(migrated.boats.includes(1));assert.ok(migrated.equipment.includes('lamp'));
 const normal=new FishingGame(),upgraded=new FishingGame({...freshSave(),equipment:['line','reel','lamp']});for(const f of[normal,upgraded]){f.phase='fight';f.pending=getCatch('eel');f.reeling=true;f.castDepth=30;advance(f,2);}assert.ok(upgraded.tension<normal.tension);assert.ok(upgraded.progress>normal.progress);upgraded.phase='caught';upgraded.resolveCatch(true);assert.equal(upgraded.save.sanity,88);
});
test('diary follows discoveries, preserves dates and gives a coherent next objective',()=>{
 const g=new FishingGame();assert.deepEqual(Object.keys(g.save.diary),['letter']);assert.match(g.objective,/Fang en fisk/);g.phase='caught';g.pending=getCatch('cod');g.resolveCatch(true);assert.ok(g.save.diary.marsh);g.save.day=4;g.phase='caught';g.pending=getCatch('compass');g.resolveCatch(true);assert.equal(g.save.diary.compass,4);assert.match(g.objective,/Blackthorn/);assert.equal(g.save.diary.idol,undefined);
 const restored=new FishingGame(JSON.parse(JSON.stringify(g.save)));assert.equal(restored.save.diary.compass,4);assert.ok(restored.unreadStory>=3);restored.save.storyRead=Object.keys(restored.save.diary);assert.equal(restored.unreadStory,0);
});
